site_name: Godash
repo_name: 'duckpunch/godash'
repo_url: 'https://github.com/duckpunch/godash'
pages:
  - Home: index.md
  - Documentation: documentation.md
theme: material
extra_css:
  - style.css
extra:
  social:
    - type: 'github'
      link: 'https://github.com/duckpunch'
